### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by Pengzw** [tuotoo/padchat#1]
```
goroutine 1 [running]:
github.com/gorilla/websocket.newConnBRW(0x83a0700, 0x18e0ec10, 0x0, 0x0, 0x7fffffff, 0x0, 0x18e55500)
	/data/www/golang/src/github.com/gorilla/websocket/conn.go:321 +0x229
github.com/gorilla/websocket.newConn(0x83a0700, 0x18e0ec10, 0x18e51e00, 0x0, 0x7fffffff, 0x18e0ec10)
	/data/www/golang/src/github.com/gorilla/websocket/conn.go:267 +0x4a
github.com/gorilla/websocket.(*Dialer).Dial(0x852c100, 0x8362297, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/www/golang/src/github.com/gorilla/websocket/client.go:280 +0x9e2
github.com/tuotoo/padchat.NewBot(0x8362297, 0x16, 0x0, 0x0, 0x852f7a0)
	/data/www/golang/src/github.com/tuotoo/padchat/bot.go:35 +0x4a
main.main()
	/data/www/golang/src/github.com/tuotoo/padchat/example/main.go:13 +0x2f
exit status 2
```
实例运行后出这个问题, 请教下

**Comment by jqs7** [comment]
扶额, 是在32位环境下运行的么? 
大概是我把 WriteBufferSize 设置得太大了的原因...

**Comment by Pengzw** [comment]
ok

**Comment by Pengzw** [comment]
@jqs7 ok
